### ISSUE TITLE
release state of library vs bitcoin-core

### ISSUE THREAD

**Issue by nessence** [bitcoin/secp256k1#264]
Is there particular commit of this repos which can be used for production, or is github.com/bitcoin the best code for applications to use?

**Comment by sipa** [comment]
There is no formal release of libsecp256k1 yet, and using it for production
purposes is discouraged.

Bitcoin Core includes a pre-release version of this library, but only for
signing, as that already provides benefits (in terms of side channel attack
protection and deterministic signing) over the old OpenSSL code. However,
that's only reasonable because signing has much lower risks, while
verification is still done by the old code.

**Comment by sipa** [comment]
In particular, the API is not stable yet.

**Comment by sipa** [comment]
Closing this issue in favor of #286.
