### ISSUE TITLE
Factory functions for opaque structs

### ISSUE THREAD

**Issue by oleganza** [bitcoin/secp256k1#288]
Function `secp256k1_ecdsa_sign` takes a pointer to `secp256k1_ecdsa_signature_t` that is considered opaque. Unfortunately, in my [Ruby FFI extension](https://github.com/oleganza/btcruby/blob/4399344b4b417f24f811fbd74e2631230550ba70/lib/btcruby/secp256k1.rb#L17-L23) I have to copy the declaration to allocate the struct with proper size. It would be nice if there were factory methods `secp256k1_ecdsa_signature_create/destroy` to allocate the struct and get the pointer to it (and destroy accordingly). Similar methods for `secp256k1_pubkey_t` as well. WDYT?

**Comment by apoelstra** [comment]
I think we should add create/clone/destroy functions for these types.

The reason they don't exist today is that as long as the struct definitions are public, they aren't needed. It's possible to allocate these objects on the stack, which is what C, C++ and Rust users (at least) are expected to prefer.

**Comment by oleganza** [comment]
Got it. I have no objection to public definitions for on-stack allocation. But for dynamic allocation i'd prefer to use the appropriate functions.

**Comment by sipa** [comment]
The definition (or at least the size) of these data structures is also
intended to be stable across versions (once the API is stable, no
guarantees at this poiny), as they break compatibility between headers and
binary otherwise.

This is intentional. I don't think regular usage of the library should
require dynamic memory. These data structures don't serve as internal
representations, only as "pre-parsed easily-accessible versions of more
complex encoded data". Adding constructors and cloning routines would add a
further layer of abstraction (not needing to know the sizes), but would
come at the cost of being unable to use them without allocation.

I think you can just hardcode the sizes. They are not intended to change.

**Comment by apoelstra** [comment]
@sipa "I don't think regular usage of the library should require dynamic memory" but in some interpreted languages I think *everything* requires dynamic memory.

**Comment by sipa** [comment]
They're free to do allocation in the wrapper then :)

**Comment by oleganza** [comment]
@sipa @apoelstra just to clarify: I don't ask for type-specific factory functions for "purity" reasons, but only if the struct is considered private. But if, like Pieter says, it's opaque and size will be (eventually) guaranteed, then there's no need for factory functions. As for the current state of the lib, I understand that it does not guarantee ABI stability, so I'll have to keep my eye on it to keep FFI binding up to date anyway.

**Comment by sipa** [comment]
To be clear: I have no problem with dynamic memory being used where needed. I just mean that these types are intended to be simple and stable enough exactly so they can be trivially used as stack-allocated types. And because of that property, it should be safe to just allocate them anywhere needed without initialization/cloning/destruction too.

**Comment by sipa** [comment]
Seems that this stability property needs documentation in the header file.

**Comment by oleganza** [comment]
@sipa :+1:

**Comment by sipa** [comment]
@oleganza The types' properties should currently be properly documented now (though significant other refactorings are underway). Do you think it is sufficient and clear enough now?

**Comment by oleganza** [comment]
@sipa docs look great now. I think this resolves the issue. Thanks!
