### ISSUE TITLE
Insuffient padding canonical?

### ISSUE THREAD

**Issue by xenog** [bitcoin/secp256k1#341]
In the Haskoin code, I have two test vectors for non-canonical signatures that are being parsed as if they were canonical:

- `0x304402208990e0584b2b238e1dfaad8d6ed69ecc1a4a13ac85fc0b31d0df395eb1ba610502202d5876262c288beb511d061691bf26777344b702b00f8fe28621fe4e566695ed`
- `0x304402205990e0584b2b238e1dfaad8d6ed69ecc1a4a13ac85fc0b31d0df395eb1ba61050220fd5876262c288beb511d061691bf26777344b702b00f8fe28621fe4e566695ed`

The first one has insufficient padding in `r` and the second one has insufficient padding in `s`, meaning they are negative numbers in ASN.1 `IntVar` format. These test vectors are detected as non-canonical signatures by Haskoin's canonical DER parser, but since I moved to this secp256k1 library, the vectors are considered valid by the default strict parser.

**Comment by xenog** [comment]
I did further testing, and I found that signatures above parse incorrectly, albeit successfully.

When I import both signatures above, and I re-export them as DER I get:

- `0x302502010002202d5876262c288beb511d061691bf26777344b702b00f8fe28621fe4e566695ed`
- `0x302502205990e0584b2b238e1dfaad8d6ed69ecc1a4a13ac85fc0b31d0df395eb1ba6105020100`

Notice how the negative numbers are just zero:

- r: `0x00`, s: `0x2d5876262c288beb511d061691bf26777344b702b00f8fe28621fe4e566695ed`
- r: `0x5990e0584b2b238e1dfaad8d6ed69ecc1a4a13ac85fc0b31d0df395eb1ba6105`, s: `0x00`

**Comment by gmaxwell** [comment]
See the documentation for secp256k1_ecdsa_signature_parse_der:

 *  This function will accept any valid DER encoded signature, even if the   
 *  encoded numbers are out of range.
 *
 *  After the call, sig will always be initialized. If parsing failed or the
 *  encoded numbers are out of range, signature validation with it is
 *  guaranteed to fail for every message and public key.

**Comment by xenog** [comment]
Yeah, I expect the parser to return false, so that I know that the parsed signature contains out-of-range numbers.

**Comment by sipa** [comment]
I tried to completely separate the "valid encoding" from "valid signature".
If you're going to mix the two, you get very hard to get
consensus-compatible behaviour. Checking for out of range values is not
something you expect a DER parser to do.

**Comment by gmaxwell** [comment]
I presume this expectation was due to BIP66.

BIP66 is stricter than canonical DER and needed to be because most underlying ECDSA implementations using in Bitcoin land will not just parse _pass_  signatures which are validly encoded invalid signatures (e.g. OpenSSL decodes like an unsigned value always).  So if BIP66 had limited itself to only restricting things to canonical DER the network consensus would still depend on crazy implementation specific behavior in underlying signature libraries.

Based on your comments we'll go review BIP66 to make it clear that the BIP66 test is stricter in this manner.

**Comment by xenog** [comment]
I would expect the DER parser to produce negative numbers if that is what the DER-encoded data contains. But the function I am interacting with is not only a DER parser, but it should also interpret the data within as a signature, and that is where my expectations aren't met.

I expect that if the DER data encodes out-of-range numbers for secp256k1, the decoder should fail. Although the signature might be valid DER, the data encoded therein makes no sense in a secp256k1 ECDSA signature. Stating that the signature was decoded correctly, and then putting in a single zero byte in *r* or *s* because the number was negative does not seem correct. It breaks the expected equality between identity and composition of decoding and encoding functions.

For the time being I will make my wrapper function in Haskoin detect if *r* or *s* is zero and fail, but it would be great if the failure condition came from the underlying C code.

**Comment by xenog** [comment]
By the way, reviewing the [SEC specification for ECDSA](http://www.secg.org/sec1-v2.pdf), it says this in section 4.1.4 as step 1 in signature verification:

> If *r* and *s* are not both integers in the interval [1, *n* - 1], output “invalid” and stop.

Granted, this is done at the verification stage, and not during decoding, but if the signature is so obviously invalid with a zero-byte in any *r* or *s*, why not fail at decoding?

**Comment by sipa** [comment]
But exactly what tests should be done?
* BIP66 specifies max 32 bytes for R and S, because that's much sinpler to
implement than an accurate range check, and has no additional DoS risk.
* You seem to suggest that values 0 or >= order should be rejected because
the implementation-specific representation if numbers inside libsecp256k1
can't deal with them, so they are "obviously" invalid.
* What about values of r that are not equal to a valid x coordinate mod
order? Those are also guaranteed to be invalid signatures, and a different
implementation that decompresses the r value into one or two points ahead
of time would equally "obviously" detect such failure.

All of these additional constraints are arbitrary, so which one do you
pick? For some applications the distinction between incorrect parse and
invalid signature matters, and we shouldn't be introducing any extra
standards just because our signature parser is smart enough to detect some
cases already.

**Comment by xenog** [comment]
Yeah, I guess the rabbit hole can go quite deep. I think it is cool if these problems with signatures could be detected at decode instead of verification time, but I understand it is a design decision not to. I have added code in Haskoin that considers signatures where *r* or *s* is zero to be invalid. My test suite is happy. I'll close this issue.

**Comment by sipa** [comment]
One suggestion that @gmaxwell came up with is to make the serialize
function fail on such signatures.

Advantage: there is no "DER parse succeeds, but reserialize results in
something else" behaviour.

Disadvantage: there is a " DER parse succeeds but cannot serialize"
behaviour.

I don't know whether it makes much of a difference, but I'd like to know
what others think. I believe it's unfortunate that either is necessary, but
the alternative is arbitrary-sized secp256k1_ecdsa_signature data types,
which I think is way worse.

**Comment by gmaxwell** [comment]
This still, of course, leaves us with a parse-is-successful-serialize-is-successful when r nor n-r is a quadratic residue in Fp.

**Comment by peterdettman** [comment]
@sipa Not sure of the best place to mention this, but it strikes me that BIP 66's IsValidSignatureEncoding (as I read it here: https://github.com/bitcoin/bips/blob/master/bip-0066.mediawiki) does not prevent one of R or S being longer than 33 bytes. The sig.size() > 73 check implies that is invalid. Also, at 33 bytes, the first octet MUST be zero?

I would like to see clearer comments on which checks are DER strictness checks per se, and which are signature strictness checks (i.e. the negative values check, the overall size check, the prospective checks I mention above). Probably it would benefit from actually factoring the DER checks into a separate "method".
